package com.example.myapplication;

import android.content.Context;
import android.os.Bundle;
import android.support.annotation.Nullable;
import android.support.v4.app.Fragment;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.AdapterViewFlipper;
import android.widget.BaseAdapter;
import android.widget.ExpandableListView;
import android.widget.ImageView;
import android.widget.TextView;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;

public class Fragment_coe_fac extends Fragment {

    AdapterViewFlipper adapterViewFlipper;
    int[] images={
            R.drawable.coe_one,
            R.drawable.coe_two,
            R.drawable.coe_threee,
            R.drawable.coe_four,
            R.drawable.coe_five,

    };
    String[] text={
            "MOISTURE MANAGEMENT TESTER",
            "SYNTHETIC BLOOD PENETRATION RESISTANCE TESTER",
            "THE HIGH PERFORMANCE THIN LAYER CHROMATOGRAPHY",
            "BACTERIAL FILTRATION EFFICIENCY",
            "FIELD EMISSION SCANNING ELECTRON MICROSCOPE",
    };
    String[] details={
            "Moisture management tester is used to measure the comfort property of a fabric. The parameters that can be measured are as follows, wetting time (sec), absorption rate (%/sec), maximum wetted radius (mm), spreading speed (mm/sec), one way transport capability(R) and overall moisture management capability (OMMC). The materials that can be tested are wound dressings, sportswear and ordinary textile materials. This instrument works in accordance with International standard AATCC 195.",
            "The Synthetic blood penetration resistance tester is used to evaluate the barrier performance of fabrics used as surgical gowns /drapes in high risk surgeries. The specimen to be tested is subjected to choking in synthetic blood / bacteriophage solution and penetration through the fabric is checked. This instrument can perform two tests as per International standard ASTM F-1670 (Resistance to synthetic blood) and ASTM F-1671 (Resistance to blood borne pathogens). All types of fabrics that can be used for high risk surgeries can be tested.",
            "The High Performance Thin Layer Chromatography is a mode of liquid chromatography in which the sample is applied as a small spot or streak to the origin of a thin absorbent layer TLC can be used for analytical purpose and preparative technique. TLC provides separations in milligram and microgram ranges. Separated substances can be analyzed for further characterization by other techniques such as GC- MS, HPLC, UV-VIS, FT-IR etc..,",
            "This instrument is used to measure The Bacterial filtration efficiency of medical textile materials, employing a ratio of the upstream bacterial challenge to downstream residual concentration to determine filtration efficiency of medical textile materials. It is a quantitative method that allows filtration efficiency for medical textile products to be determined. The maximum filtration efficiency that can be determined using this instrument is 99.9%.This instrument works accordance with the standard ASTM F 2101.",
            "The Field Emission Scanning Electron Microscope can be used to determine the surface characteristics of any medical textile product. The electrons generated by a field emission source are focused on to the specimen. As a result of this, secondary electrons are emitted from the specimen through which the surface characteristics of the specimen are analyzed.",
    };

    ExpandableListView expandableListView;
    HashMap<String, List<String>> listChild;
    List<String>listHeader;
    Expandable_phy_adapter expandable_phy_adapter;



    @Override
    @Nullable
    public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstancetate) {
        View view = inflater.inflate(R.layout.fragment_physics_fac, container, false);
        adapterViewFlipper=(AdapterViewFlipper)view.findViewById(R.id.adapterViewFlipper_phy);
        CusAdap cusAdap=new CusAdap(getActivity(),images,details,text);
        adapterViewFlipper.setAdapter(cusAdap);
        adapterViewFlipper.setFlipInterval(3000);
        adapterViewFlipper.setAutoStart(true);


        expandableListView=(ExpandableListView)view.findViewById(R.id.expListView_phy);
        listChild=ExpandableListDataCoe.getData();
        listHeader=new ArrayList<String>(listChild.keySet());
        expandable_phy_adapter=new Expandable_phy_adapter(getActivity(),listHeader,listChild);
        expandableListView.setAdapter(expandable_phy_adapter);
        return view;
    }



}
class CusAdapp extends BaseAdapter {
    Context context;
    int[] images;
    String[] s_text;
    String[] s_head;
    LayoutInflater inflater;

    public CusAdapp(Context applicationContext, int[] images,String[] s_text,String[] s_head) {
        this.context = applicationContext;
        this.images = images;
        this.s_text=s_text;
        this.s_head=s_head;
        inflater = (LayoutInflater.from(applicationContext));
    }

    @Override
    public int getCount() {
        return images.length;
    }

    @Override
    public Object getItem(int position) {
        return null;
    }

    @Override
    public long getItemId(int position) {
        return 0;
    }

    @Override
    public View getView(int position, View view, ViewGroup parent) {
        view = inflater.inflate(R.layout.adapter_list_item, null);
        ImageView image = (ImageView) view.findViewById(R.id.image);
        TextView text=(TextView)view.findViewById(R.id.text_slider);
        TextView head=(TextView)view.findViewById(R.id.slide_head);

        head.setText(s_head[position]);
        text.setText(s_text[position]);
        image.setImageResource(images[position]);

        return view;
    }
}